<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; style-src 'self' 'unsafe-inline' https:;">
    <title>@yield('title', 'Plataforma DSS')</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        :root{
            --primary: #153B2E; /* dark green from logo */
            --primary-700: #0F2B22; /* darker */
            --accent: #F28C2B; /* orange accent from logo */
            --bg-start: #FFF8F1;
            --bg-end: #FFFFFF;
        }

        .site-nav{ background: var(--primary); color: white; }
        .site-footer{ background: var(--primary); color: white; }
        .site-link-hover:hover{ color: var(--accent) !important; }
        .brand-text{ color: white; }
        .site-nav a{ font-size: .95rem; }
        .site-nav .nav-link { white-space: nowrap; padding: .25rem .5rem; }
        .site-nav .nav-link i { font-size: 1.05rem; }
        @media (max-width: 768px){
            .site-nav{ padding-left: .5rem; padding-right: .5rem; }
            .site-nav .brand-text{ font-size: 1rem; }
            .site-nav .site-link-hover{ padding: .25rem .4rem; }
        }
        /* Global responsive helpers */
        img, picture { max-width: 100%; height: auto; display: inline-block; }
        video, iframe { max-width: 100%; height: auto; display: block; }
        .responsive-video { position: relative; padding-top: 56.25%; }
        .responsive-video iframe, .responsive-video video { position: absolute; top:0; left:0; width:100%; height:100%; }
        /* Make table cells wrap and avoid overflow, but prefer whole-word breaks */
        table { width: 100%; border-collapse: collapse; table-layout: auto; }
        th, td { white-space: normal; overflow-wrap: break-word; word-break: normal; }
        /* Keep header labels on one line so they don't collapse to single letters */
        thead th { white-space: nowrap; }
        /* Support both custom .table-responsive and Tailwind's .overflow-x-auto wrappers */
        .table-responsive, .overflow-x-auto { overflow-x: auto; }
        /* Mobile: hide wide tables and show card list generated by JS */
        .table-card-list { display: none; gap: 0.75rem; }
        .table-card { background: white; border: 1px solid #e5e7eb; padding: .75rem; border-radius: .5rem; box-shadow: 0 1px 2px rgba(0,0,0,0.03); }
        .table-card-row { display: flex; justify-content: space-between; gap: .5rem; padding: .25rem 0; border-bottom: 1px dashed #f3f4f6; }
        .table-card-row:last-child { border-bottom: none; }
        .table-card-label { color: #6b7280; font-size: .85rem; font-weight: 600; }
        .table-card-value { color: #111827; font-size: .95rem; text-align: right; }
        @media (max-width: 640px){
            /* Hide wide tables inside responsive wrappers and show card lists instead */
            .table-responsive table, .overflow-x-auto > table { display: none; }
            .table-card-list { display: flex; flex-direction: column; }
        }
    </style>
    @yield('extra_css')
</head>
<body class="bg-gray-50" style="--primary: #153B2E; --primary-700:#0F2B22; --accent:#F28C2B;">
    @if(Auth::check())
        <nav class="site-nav shadow-lg">
            <div class="max-w-7xl mx-auto px-4">
                        <div class="flex flex-wrap justify-between items-center h-16">
                    <div class="flex items-center">
                                <x-logo alt="logo" class="mr-3 w-8 md:w-10" />
                                <span class="font-bold text-lg brand-text hidden md:inline-block">Plataforma DSS</span>
                    </div>

                    <!-- Mobile menu button -->
                    <div class="md:hidden">
                        <button id="nav-toggle" class="text-white focus:outline-none">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                        </button>
                    </div>

                    <!-- Desktop menu -->
                    <div class="hidden md:flex items-center space-x-6 text-sm">
                        @if(Auth::user()->isAdmin())
                            <a href="{{ route('usuarios.index') }}" class="site-link-hover nav-link flex items-center">
                                <i class="fas fa-users mr-1"></i><span class="hidden sm:inline">Usuários</span>
                            </a>
                            <a href="{{ route('treinamentos.index') }}" class="site-link-hover nav-link flex items-center">
                                <i class="fas fa-video mr-1"></i><span class="hidden sm:inline">Treinamentos</span>
                            </a>
                        @endif

                        <a href="{{ route('dashboard') }}" class="site-link-hover nav-link flex items-center">
                            <i class="fas fa-home mr-1"></i><span class="hidden sm:inline">Dashboard</span>
                        </a>

                        <a href="{{ route('certificados.meus') }}" class="site-link-hover nav-link flex items-center">
                            <i class="fas fa-certificate mr-1"></i><span class="hidden sm:inline">Certificados</span>
                        </a>

                        <a href="{{ route('certificacao.conformidade') }}" class="site-link-hover nav-link flex items-center">
                            <i class="fas fa-shield-alt mr-1"></i><span class="hidden sm:inline">Transparência</span>
                        </a>

                        <div class="relative">
                            <button id="user-desktop-toggle" class="flex items-center site-link-hover">
                                <i class="fas fa-user-circle text-xl"></i>
                                <span class="ml-2 hidden sm:inline">{{ Auth::user()->nome }}</span>
                            </button>
                            <div id="user-desktop-menu" class="hidden absolute right-0 mt-0 w-44 bg-white text-gray-800 rounded shadow-lg z-50">
                                <a href="{{ route('dashboard') }}" class="block px-4 py-2 hover:bg-gray-100">
                                    <i class="fas fa-user mr-2"></i> Meu Perfil
                                </a>
                                <form action="{{ route('logout') }}" method="POST" class="block">
                                    @csrf
                                    <button type="submit" class="w-full text-left px-4 py-2 hover:bg-gray-100">
                                        <i class="fas fa-sign-out-alt mr-2"></i> Sair
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Mobile menu, hidden by default -->
                <div id="mobile-menu" class="hidden md:hidden mt-2 pb-4">
                    <div class="px-2 space-y-1">
                        @if(Auth::user()->isAdmin())
                            <a href="{{ route('usuarios.index') }}" class="block px-3 py-2 rounded text-white site-link-hover">Usuários</a>
                            <a href="{{ route('treinamentos.index') }}" class="block px-3 py-2 rounded text-white site-link-hover">Treinamentos</a>
                        @endif
                        <a href="{{ route('dashboard') }}" class="block px-3 py-2 rounded text-white site-link-hover">Dashboard</a>
                        <a href="{{ route('certificados.meus') }}" class="block px-3 py-2 rounded text-white site-link-hover">Certificados</a>
                                <a href="{{ route('certificacao.conformidade') }}" class="block px-3 py-2 rounded text-white site-link-hover">Transparência</a>

                        <div class="border-t border-white/20 mt-2 pt-2">
                            <a href="{{ route('dashboard') }}" class="block px-3 py-2 rounded text-white">Meu Perfil</a>
                            <form action="{{ route('logout') }}" method="POST" class="block px-3 py-2">
                                @csrf
                                <button type="submit" class="w-full text-left">Sair</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    @endif

    <div class="min-h-screen">
        @if($errors->any())
            <div class="max-w-7xl mx-auto mt-4 px-4">
                <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4">
                    <p class="font-bold">Erros encontrados:</p>
                    <ul class="list-disc list-inside">
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif

        @if(session('success'))
            <div class="max-w-7xl mx-auto mt-4 px-4">
                <div class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4">
                    {{ session('success') }}
                </div>
            </div>
        @endif

        @if(session('error'))
            <div class="max-w-7xl mx-auto mt-4 px-4">
                <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4">
                    {{ session('error') }}
                </div>
            </div>
        @endif

        @yield('content')
    </div>

            <footer class="site-footer mt-16 py-8">
        <div class="max-w-7xl mx-auto px-4 text-center">
            <p>&copy; 2026 64 Bits Soluções. Todos os direitos reservados.</p>
        </div>
    </footer>

    <script>
        (function(){
            const navToggle = document.getElementById('nav-toggle');
            const mobileMenu = document.getElementById('mobile-menu');
            const userDesktopToggle = document.getElementById('user-desktop-toggle');
            const userDesktopMenu = document.getElementById('user-desktop-menu');

            if(navToggle && mobileMenu){
                navToggle.addEventListener('click', function(){
                    mobileMenu.classList.toggle('hidden');
                });
            }

            if(userDesktopToggle && userDesktopMenu){
                userDesktopToggle.addEventListener('click', function(e){
                    e.stopPropagation();
                    userDesktopMenu.classList.toggle('hidden');
                });

                // close when clicking outside
                document.addEventListener('click', function(){
                    if(!userDesktopMenu.classList.contains('hidden')){
                        userDesktopMenu.classList.add('hidden');
                    }
                });
            }
        })();
        // Transform tables inside .table-responsive into card lists on small screens
        (function(){
            const BREAKPOINT = 640;
            function transformTables(){
                document.querySelectorAll('.table-responsive, .overflow-x-auto').forEach(function(container){
                    const table = container.querySelector('table');
                    if(!table) return;
                    // ensure we only process once per container
                    if(container.querySelector('.table-card-list')) return;

                    const thead = table.querySelector('thead');
                    const headers = [];
                    if(thead){
                        thead.querySelectorAll('th').forEach(h => headers.push(h.textContent.trim()));
                    }

                    const list = document.createElement('div');
                    list.className = 'table-card-list';

                    const tbody = table.querySelector('tbody');
                    if(!tbody) return;
                    tbody.querySelectorAll('tr').forEach(function(row){
                        const card = document.createElement('div');
                        card.className = 'table-card';
                        const cells = row.querySelectorAll('td');
                        cells.forEach(function(cell, idx){
                            const rowDiv = document.createElement('div');
                            rowDiv.className = 'table-card-row';
                            const label = document.createElement('div');
                            label.className = 'table-card-label';
                            label.textContent = headers[idx] || '';
                            const value = document.createElement('div');
                            value.className = 'table-card-value';
                            value.innerHTML = cell.innerHTML;
                            rowDiv.appendChild(label);
                            rowDiv.appendChild(value);
                            card.appendChild(rowDiv);
                        });
                        list.appendChild(card);
                    });

                    container.appendChild(list);
                });
            }

            function onResize(){
                if(window.innerWidth <= BREAKPOINT){
                    transformTables();
                }
            }

            window.addEventListener('resize', onResize);
            document.addEventListener('DOMContentLoaded', onResize);
            // also run immediately in case DOM already loaded
            setTimeout(onResize, 50);
        })();
    </script>
    @yield('extra_js')
</body>
</html>
