<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' 'unsafe-eval' https:; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:; style-src 'self' 'unsafe-inline' https:;">
    <title>@yield('title', 'Plataforma DSS')</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        :root{
            --primary: #153B2E; /* dark green from logo */
            --primary-700: #0F2B22; /* darker */
            --accent: #F28C2B; /* orange accent from logo */
            --bg-start: #FFF8F1;
            --bg-end: #FFFFFF;
        }

        .site-nav{ background: var(--primary); color: white; }
        .site-footer{ background: var(--primary); color: white; }
        .site-link-hover:hover{ color: var(--accent) !important; }
        .brand-text{ color: white; }
        .site-nav a{ font-size: .95rem; }
        .site-nav .nav-link { white-space: nowrap; padding: .25rem .5rem; }
        .site-nav .nav-link i { font-size: 1.05rem; }
        @media (max-width: 768px){
            .site-nav{ padding-left: .5rem; padding-right: .5rem; }
            .site-nav .brand-text{ font-size: 1rem; }
            .site-nav .site-link-hover{ padding: .25rem .4rem; }
        }
        /* Global responsive helpers */
        img, picture { max-width: 100%; height: auto; display: inline-block; }
        video, iframe { max-width: 100%; height: auto; display: block; }
        .responsive-video { position: relative; padding-top: 56.25%; }
        .responsive-video iframe, .responsive-video video { position: absolute; top:0; left:0; width:100%; height:100%; }
        /* Make table cells wrap and avoid overflow, but prefer whole-word breaks */
        table { width: 100%; border-collapse: collapse; table-layout: auto; }
        th, td { white-space: normal; overflow-wrap: break-word; word-break: normal; }
        /* Keep header labels on one line so they don't collapse to single letters */
        thead th { white-space: nowrap; }
        /* Support both custom .table-responsive and Tailwind's .overflow-x-auto wrappers */
        .table-responsive, .overflow-x-auto { overflow-x: auto; }
        /* Mobile: hide wide tables and show card list generated by JS */
        .table-card-list { display: none; gap: 0.75rem; }
        .table-card { background: white; border: 1px solid #e5e7eb; padding: .75rem; border-radius: .5rem; box-shadow: 0 1px 2px rgba(0,0,0,0.03); }
        .table-card-row { display: flex; justify-content: space-between; gap: .5rem; padding: .25rem 0; border-bottom: 1px dashed #f3f4f6; }
        .table-card-row:last-child { border-bottom: none; }
        .table-card-label { color: #6b7280; font-size: .85rem; font-weight: 600; }
        .table-card-value { color: #111827; font-size: .95rem; text-align: right; }
        @media (max-width: 640px){
            /* Hide wide tables inside responsive wrappers and show card lists instead */
            .table-responsive table, .overflow-x-auto > table { display: none; }
            .table-card-list { display: flex; flex-direction: column; }
        }
    </style>
    @yield('extra_css')
</head>
<body class="bg-gray-50" style="--primary: #153B2E; --primary-700:#0F2B22; --accent:#F28C2B;">
    @if(Auth::check())
        @php
            $epiAlertaCount = 0;
            if (Auth::check() && (Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('epi'))) {
                try {
                    if (\Illuminate\Support\Facades\Schema::hasTable('ss_epi')) {
                        $epiAlertaCount = \App\Models\Epi::contarCaCriticos(30)['total'];
                    }
                } catch (\Throwable $e) {}
            }
            $treinamentosAlertaCount = 0;
            if (Auth::check() && (Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('trainings', 'view'))) {
                $treinamentosAlertaCount = \App\Models\Certificate::contarValidadesCriticas(30);
            }
        @endphp
        <nav class="site-nav shadow-lg">
            <div class="max-w-7xl mx-auto px-4">
                <div class="flex justify-between items-center h-16">
                    <div class="flex items-center space-x-3">
                        <a href="{{ route('dashboard') }}" class="flex items-center gap-2">
                            <x-logo alt="logo" class="w-8 md:w-10" />
                            <span class="font-bold text-lg brand-text hidden md:inline-block">Plataforma DSS</span>
                        </a>
                    </div>

                    <!-- Mobile menu button -->
                    <div class="md:hidden">
                        <button id="nav-toggle" class="text-white focus:outline-none p-1">
                            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                        </button>
                    </div>

                    <!-- Desktop menu -->
                    <div class="hidden md:flex items-center space-x-4 lg:space-x-5 text-sm">
                        <a href="{{ route('dashboard') }}" class="site-link-hover nav-link flex items-center">
                            <i class="fas fa-home mr-1.5"></i><span>Dashboard</span>
                        </a>

                        @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('epi'))
                            <a href="{{ route('epi.index') }}" class="site-link-hover nav-link flex items-center text-amber-300 hover:text-amber-200 font-semibold">
                                <i class="fas fa-hard-hat mr-1.5"></i><span>Gestão de EPIs</span>
                                @if($epiAlertaCount > 0)
                                    <span class="ml-1.5 inline-flex items-center justify-center min-w-5 h-5 px-1.5 bg-rose-500 text-white text-[10px] font-bold rounded-full" title="Itens com CA vencido, vencendo ou sem validade">● {{ $epiAlertaCount }}</span>
                                @endif
                            </a>
                        @endif

                        @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('trainings', 'view'))
                            <a href="{{ route('treinamentos.index') }}" class="site-link-hover nav-link flex items-center">
                                <i class="fas fa-video mr-1.5"></i><span>Treinamentos</span>
                                @if($treinamentosAlertaCount > 0)
                                    <span class="ml-1.5 inline-flex items-center justify-center min-w-5 h-5 px-1.5 bg-rose-500 text-white text-[10px] font-bold rounded-full" title="{{ $treinamentosAlertaCount }} certificado(s) de treinamento vencidos ou vencendo em 30 dias">● {{ $treinamentosAlertaCount }}</span>
                                @endif
                            </a>
                        @endif

                        @if(Auth::user()->hasPermission('social', 'view'))
                            <a href="{{ route('social.feed') }}" class="site-link-hover nav-link flex items-center">
                                <i class="fas fa-hashtag mr-1.5"></i><span>Feed Social</span>
                            </a>
                        @endif

                        @if(!Auth::user()->isAdmin() && !Auth::user()->isSuperAdmin())
                            <a href="{{ route('certificados.meus') }}" class="site-link-hover nav-link flex items-center">
                                <i class="fas fa-certificate mr-1.5"></i><span>Certificados</span>
                            </a>
                        @endif

                        <a href="{{ route('certificacao.conformidade') }}" class="site-link-hover nav-link flex items-center">
                            <i class="fas fa-shield-alt mr-1.5"></i><span>Transparência</span>
                        </a>

                        @if(Auth::user()->isAdmin() || Auth::user()->isSuperAdmin())
                            <div class="relative">
                                <button id="admin-desktop-toggle" type="button" class="site-link-hover nav-link flex items-center focus:outline-none cursor-pointer">
                                    <i class="fas fa-cog mr-1.5"></i><span>Administração</span>
                                    <i class="fas fa-chevron-down text-xs ml-1 opacity-75"></i>
                                </button>
                                <div id="admin-desktop-menu" class="hidden absolute right-0 mt-2 w-56 bg-white text-gray-800 rounded-lg shadow-xl z-50 border border-gray-200 py-1 text-sm">
                                    @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('users', 'view'))
                                        <a href="{{ route('usuarios.index') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-gray-700 hover:text-emerald-900">
                                            <i class="fas fa-users w-5 mr-2 text-emerald-700"></i> Usuários & Fichas
                                        </a>
                                    @endif
                                    @if(Auth::user()->isSuperAdmin())
                                        <a href="{{ route('certificados.gerencial') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-gray-700 hover:text-emerald-900">
                                            <i class="fas fa-certificate w-5 mr-2 text-blue-600"></i> Consulta Certificados
                                        </a>
                                    @endif
                                    @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('rankings', 'view'))
                                        <a href="{{ route('admin.ranking.index') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-gray-700 hover:text-emerald-900">
                                            <i class="fas fa-trophy w-5 mr-2 text-amber-500"></i> Ranking
                                        </a>
                                    @endif
                                    @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('projeto_pedagogico', 'view'))
                                        <a href="{{ route('projetos-pedagogicos.index') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-gray-700 hover:text-emerald-900">
                                            <i class="fas fa-book-open w-5 mr-2 text-blue-700"></i> Projetos Pedagógicos
                                        </a>
                                    @endif
                                    @if(Auth::user()->isSuperAdmin())
                                        <a href="{{ route('admin.ranking.settings') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-gray-700 hover:text-emerald-900">
                                            <i class="fas fa-sliders-h w-5 mr-2 text-gray-600"></i> Parâmetros Ranking
                                        </a>
                                        <a href="{{ route('relatorios.ia') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-gray-700 hover:text-emerald-900">
                                            <i class="fas fa-chart-line w-5 mr-2 text-indigo-600"></i> Relatórios IA
                                        </a>
                                    @endif
                                    @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('splash', 'view'))
                                        <a href="{{ route('admin.splash.index') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-gray-700 hover:text-emerald-900">
                                            <i class="fas fa-bullhorn w-5 mr-2 text-orange-500"></i> Avisos / Splash
                                        </a>
                                    @endif
                                    @if(Auth::user()->isSuperAdmin())
                                        <a href="{{ route('admin.permissoes.index') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-gray-700 hover:text-emerald-900 border-t border-gray-100">
                                            <i class="fas fa-user-shield w-5 mr-2 text-purple-600"></i> Permissões
                                        </a>
                                    @endif
                                </div>
                            </div>
                        @endif

                        @php
                            $pendentesCount = 0;
                            if (Auth::check() && request()->route() && !in_array(request()->route()->getName(), ['login', 'home'])) {
                                try {
                                    if (\Illuminate\Support\Facades\Schema::hasTable('ss_colaborador') && \Illuminate\Support\Facades\Schema::hasTable('ss_epi_entrega')) {
                                        $colab = \App\Models\EpiColaborador::where('ss_c_tx_cpf', Auth::user()->cpf)->first();
                                        if ($colab) {
                                            $pendentesCount = \App\Models\EpiEntrega::pendentesAssinatura($colab->ss_c_nb_id)->count();
                                        }
                                    }
                                } catch (\Throwable $e) {}
                            }
                        @endphp
                        @if($pendentesCount > 0)
                            <a href="{{ route('epi.assinaturas') }}" class="relative site-link-hover nav-link flex items-center text-amber-300 font-bold" title="Assinaturas Pendentes">
                                <i class="fas fa-bell text-lg"></i>
                                <span class="absolute -top-1 -right-1 bg-rose-500 text-white text-[10px] font-bold rounded-full w-4 h-4 flex items-center justify-center">{{ $pendentesCount > 9 ? '9+' : $pendentesCount }}</span>
                            </a>
                        @endif

                        <div class="relative pl-2 border-l border-white/20">
                            <button id="user-desktop-toggle" type="button" class="flex items-center gap-2 site-link-hover hover:opacity-80 transition cursor-pointer">
                                @component('components.user-avatar', ['user' => Auth::user(), 'size' => 'sm'])
                                @endcomponent
                                <span class="ml-1 hidden sm:inline text-sm font-medium">{{ Auth::user()->nome }}</span>
                                <i class="fas fa-chevron-down text-xs opacity-75"></i>
                            </button>
                            <div id="user-desktop-menu" class="hidden absolute right-0 mt-2 w-56 bg-white text-gray-800 rounded-lg shadow-xl z-50 border border-gray-200 py-1">
                                <div class="px-4 py-3 border-b border-gray-200">
                                    <div class="flex items-center gap-3">
                                        <img 
                                            src="{{ Auth::user()->getFotoPerfilUrl() }}" 
                                            alt="{{ Auth::user()->nome }}"
                                            class="w-10 h-10 rounded-full object-cover border-2 border-emerald-900"
                                        >
                                        <div class="flex-1 min-w-0">
                                            <p class="text-sm font-semibold text-gray-900 truncate">{{ Auth::user()->nome }}</p>
                                            <p class="text-xs text-gray-500 truncate capitalize">{{ Auth::user()->tipo_usuario }}</p>
                                        </div>
                                    </div>
                                </div>
                                <a href="{{ route('profile.edit') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-sm text-gray-700">
                                    <i class="fas fa-camera w-5 mr-2 text-blue-600"></i> Editar Perfil
                                </a>
                                <a href="{{ route('dashboard') }}" class="flex items-center px-4 py-2 hover:bg-gray-100 text-sm text-gray-700">
                                    <i class="fas fa-user w-5 mr-2 text-emerald-700"></i> Meu Perfil
                                </a>
                                <form action="{{ route('logout') }}" method="POST" class="block border-t border-gray-200 mt-1 pt-1">
                                    @csrf
                                    <button type="submit" class="w-full flex items-center text-left px-4 py-2 hover:bg-gray-100 text-sm text-red-600">
                                        <i class="fas fa-sign-out-alt w-5 mr-2"></i> Sair
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Mobile menu, hidden by default -->
                <div id="mobile-menu" class="hidden md:hidden mt-2 pb-4 border-t border-white/10 pt-2">
                    <div class="px-2 space-y-1">
                        <a href="{{ route('dashboard') }}" class="block px-3 py-2 rounded text-white site-link-hover font-medium">
                            <i class="fas fa-home mr-2"></i> Dashboard
                        </a>
                        @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('epi'))
                            <a href="{{ route('epi.index') }}" class="block px-3 py-2 rounded text-amber-300 site-link-hover font-medium">
                                <i class="fas fa-hard-hat mr-2"></i> Gestão de EPIs
                                @if($epiAlertaCount > 0)
                                    <span class="ml-1 px-1.5 py-0.5 bg-rose-500 text-white text-xs rounded-full">{{ $epiAlertaCount }}</span>
                                @endif
                            </a>
                        @endif
                        @if($pendentesCount > 0)
                            <a href="{{ route('epi.assinaturas') }}" class="block px-3 py-2 rounded text-amber-300 site-link-hover font-bold">
                                <i class="fas fa-bell mr-2"></i> Assinaturas Pendentes
                                <span class="ml-1 px-1.5 py-0.5 bg-rose-500 text-white text-xs rounded-full">{{ $pendentesCount }}</span>
                            </a>
                        @endif
                        @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('trainings', 'view'))
                            <a href="{{ route('treinamentos.index') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                <i class="fas fa-video mr-2"></i> Treinamentos
                                @if($treinamentosAlertaCount > 0)
                                    <span class="ml-1 px-1.5 py-0.5 bg-rose-500 text-white text-xs rounded-full">{{ $treinamentosAlertaCount }}</span>
                                @endif
                            </a>
                        @endif
                        @if(Auth::user()->hasPermission('social', 'view'))
                            <a href="{{ route('social.feed') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                <i class="fas fa-hashtag mr-2"></i> Feed Social
                            </a>
                        @endif
                        @if(!Auth::user()->isAdmin() && !Auth::user()->isSuperAdmin())
                            <a href="{{ route('certificados.meus') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                <i class="fas fa-certificate mr-2"></i> Certificados
                            </a>
                        @endif
                        <a href="{{ route('certificacao.conformidade') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                            <i class="fas fa-shield-alt mr-2"></i> Transparência
                        </a>

                        @if(Auth::user()->isAdmin() || Auth::user()->isSuperAdmin())
                            <div class="border-t border-white/20 mt-2 pt-2">
                                <p class="px-3 text-xs uppercase tracking-wider text-emerald-300 font-semibold mb-1">Administração</p>
                                @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('users', 'view'))
                                    <a href="{{ route('usuarios.index') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                        <i class="fas fa-users mr-2"></i> Usuários & Fichas
                                    </a>
                                @endif
                                @if(Auth::user()->isSuperAdmin())
                                    <a href="{{ route('certificados.gerencial') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                        <i class="fas fa-certificate mr-2"></i> Consulta Certificados
                                    </a>
                                @endif
                                @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('rankings', 'view'))
                                    <a href="{{ route('admin.ranking.index') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                        <i class="fas fa-trophy mr-2 text-amber-400"></i> Ranking
                                    </a>
                                @endif
                                @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('projeto_pedagogico', 'view'))
                                    <a href="{{ route('projetos-pedagogicos.index') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                        <i class="fas fa-book-open mr-2"></i> Projetos Pedagógicos
                                    </a>
                                @endif
                                @if(Auth::user()->isSuperAdmin())
                                    <a href="{{ route('admin.ranking.settings') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                        <i class="fas fa-sliders-h mr-2"></i> Parâmetros Ranking
                                    </a>
                                    <a href="{{ route('relatorios.ia') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                        <i class="fas fa-chart-line mr-2"></i> Relatórios IA
                                    </a>
                                @endif
                                @if(Auth::user()->isSuperAdmin() || Auth::user()->hasPermission('splash', 'view'))
                                    <a href="{{ route('admin.splash.index') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                        <i class="fas fa-bullhorn mr-2"></i> Avisos / Splash
                                    </a>
                                @endif
                                @if(Auth::user()->isSuperAdmin())
                                    <a href="{{ route('admin.permissoes.index') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                        <i class="fas fa-user-shield mr-2"></i> Permissões
                                    </a>
                                @endif
                            </div>
                        @endif

                        <div class="border-t border-white/20 mt-2 pt-2">
                            <a href="{{ route('profile.edit') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                <i class="fas fa-camera mr-2 text-blue-400"></i> Editar Perfil
                            </a>
                            <a href="{{ route('dashboard') }}" class="block px-3 py-2 rounded text-white site-link-hover">
                                <i class="fas fa-user mr-2 text-emerald-400"></i> Meu Perfil
                            </a>
                            <form action="{{ route('logout') }}" method="POST" class="block px-3 py-2">
                                @csrf
                                <button type="submit" class="w-full text-left text-red-300 hover:text-red-200">
                                    <i class="fas fa-sign-out-alt mr-2"></i> Sair
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    @endif

    <div class="min-h-screen">
        @if($errors->any())
            <div class="max-w-7xl mx-auto mt-4 px-4">
                <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4">
                    <p class="font-bold">Erros encontrados:</p>
                    <ul class="list-disc list-inside">
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif

        @if(session('success'))
            <div class="max-w-7xl mx-auto mt-4 px-4">
                <div class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4">
                    {{ session('success') }}
                </div>
            </div>
        @endif

        @if(session('error'))
            <div class="max-w-7xl mx-auto mt-4 px-4">
                <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4">
                    {{ session('error') }}
                </div>
            </div>
        @endif

        @yield('content')
    </div>

    {{-- ══════════════════════════════════════════════════════════════════
         SPLASH COPA DO MUNDO 2026 — aparece uma vez por login, para todos
    ══════════════════════════════════════════════════════════════════════ --}}
    @if(session()->pull('show_copa_splash'))
    <div id="copa-splash"
         aria-modal="true" role="dialog" aria-label="Bem-vindo à Copa do Mundo 2026"
         class="fixed inset-0 z-[9999] flex flex-col items-center justify-center overflow-hidden select-none"
         style="background: linear-gradient(160deg, #009c3b 0%, #006622 40%, #ffdf00 100%);">

        <canvas id="copa-confetti" class="absolute inset-0 w-full h-full pointer-events-none"></canvas>

        <div class="relative z-10 flex flex-col items-center gap-6 px-6 text-center">

            <div style="font-size:7rem;line-height:1;animation:ballSpin 1.8s linear infinite,ballBounce .9s ease-in-out infinite alternate;">
                ⚽
            </div>

            <div style="animation:fadeSlideUp .6s ease .2s both;">
                <p class="text-5xl md:text-6xl font-black text-white drop-shadow-lg tracking-tight leading-none">
                    🇧🇷 BRASIL NA COPA! 🇧🇷
                </p>
                <p class="mt-3 text-xl md:text-2xl font-bold text-yellow-300 drop-shadow">
                    Copa do Mundo 2026
                </p>
            </div>

            <div style="animation:fadeSlideUp .6s ease .45s both;"
                 class="bg-white/15 backdrop-blur-sm border border-white/30 rounded-2xl px-8 py-4 max-w-lg">
                <p class="text-lg md:text-xl font-semibold text-white leading-relaxed">
                    "Assim como o Brasil busca o hexa com dedicação e trabalho em equipe,
                    <span class="text-yellow-300 font-black">você também faz a diferença</span>
                    na segurança da nossa frota!"
                </p>
            </div>

            <button onclick="fecharCopaSplash()"
                    style="animation:fadeSlideUp .6s ease .7s both;"
                    class="mt-2 flex items-center gap-2 bg-yellow-400 hover:bg-yellow-300 active:scale-95 text-green-900 font-black text-lg px-8 py-3 rounded-full shadow-xl transition-all focus:outline-none focus:ring-4 focus:ring-yellow-200">
                <i class="fas fa-futbol"></i>
                Vamos que vamos!
            </button>

            <div class="w-56 h-1.5 bg-white/25 rounded-full overflow-hidden" style="animation:fadeSlideUp .6s ease .8s both;">
                <div id="copa-progress" class="h-full bg-yellow-400 rounded-full"
                     style="width:100%;transition:width 8s linear;"></div>
            </div>
            <p class="text-white/70 text-xs -mt-4" style="animation:fadeSlideUp .6s ease .9s both;">
                Fechando automaticamente em 8s
            </p>
        </div>

        <style>
            @keyframes ballSpin    { to { transform: rotate(360deg); } }
            @keyframes ballBounce  { to { transform: translateY(-18px); } }
            @keyframes fadeSlideUp {
                from { opacity:0; transform:translateY(22px); }
                to   { opacity:1; transform:translateY(0); }
            }
            @keyframes splashOut   { to { opacity:0; transform:scale(1.04); pointer-events:none; } }
            #copa-splash.closing   { animation: splashOut .45s ease forwards; }
        </style>

        <script>
            (function () {
                const canvas = document.getElementById('copa-confetti');
                const ctx    = canvas.getContext('2d');
                const colors = ['#ffdf00','#009c3b','#ffffff','#3e9bdc','#f4a500','#aee571'];
                let pieces   = [];

                function resize() { canvas.width = window.innerWidth; canvas.height = window.innerHeight; }
                resize();
                window.addEventListener('resize', resize);

                for (let i = 0; i < 140; i++) {
                    pieces.push({
                        x: Math.random() * window.innerWidth,
                        y: Math.random() * window.innerHeight - window.innerHeight,
                        w: Math.random() * 10 + 5,
                        h: Math.random() * 6 + 3,
                        color: colors[Math.floor(Math.random() * colors.length)],
                        rot: Math.random() * 360,
                        vx: (Math.random() - .5) * 1.5,
                        vy: Math.random() * 2.5 + 1.2,
                        vr: (Math.random() - .5) * 4,
                    });
                }

                let rafId;
                function draw() {
                    ctx.clearRect(0, 0, canvas.width, canvas.height);
                    pieces.forEach(p => {
                        ctx.save();
                        ctx.translate(p.x + p.w / 2, p.y + p.h / 2);
                        ctx.rotate(p.rot * Math.PI / 180);
                        ctx.fillStyle = p.color;
                        ctx.fillRect(-p.w / 2, -p.h / 2, p.w, p.h);
                        ctx.restore();
                        p.x += p.vx; p.y += p.vy; p.rot += p.vr;
                        if (p.y > canvas.height) { p.y = -p.h; p.x = Math.random() * canvas.width; }
                    });
                    rafId = requestAnimationFrame(draw);
                }
                draw();
                window._copaCancelRaf = () => {
                    cancelAnimationFrame(rafId);
                    ctx.clearRect(0, 0, canvas.width, canvas.height);
                };
            })();

            setTimeout(() => { const b = document.getElementById('copa-progress'); if (b) b.style.width = '0%'; }, 50);
            setTimeout(fecharCopaSplash, 8500);

            function fecharCopaSplash() {
                const splash = document.getElementById('copa-splash');
                if (!splash || splash.classList.contains('closing')) return;
                if (window._copaCancelRaf) window._copaCancelRaf();
                splash.classList.add('closing');
                setTimeout(() => splash.remove(), 460);
            }

            document.getElementById('copa-splash').addEventListener('click', function (e) {
                if (e.target === this) fecharCopaSplash();
            });

            document.addEventListener('keydown', function (e) {
                if (e.key === 'Escape') fecharCopaSplash();
            });
        </script>
    </div>
    @endif

    {{-- ══════════════════════════════════════════════════════════════════
         SPLASH MANAGER - Conteúdos dinâmicos configurados pelo Super Admin
    ══════════════════════════════════════════════════════════════════════ --}}
    @if(session()->has('splash_contents'))
        <div id="splash-manager-modal"
             aria-modal="true" role="dialog" aria-label="Mensagem de Boas-vindas"
             class="fixed inset-0 z-[9999] hidden items-center justify-center bg-black/70 backdrop-blur-sm p-4">

            <div class="bg-white rounded-2xl shadow-2xl w-full max-w-2xl overflow-hidden relative">
                <button onclick="closeSplashManagerModal()"
                        class="absolute top-4 right-4 text-gray-400 hover:text-gray-600 z-10">
                    <i class="fas fa-times text-xl"></i>
                </button>

                <div id="splash-content-carousel" class="relative">
                    @foreach(session('splash_contents') as $index => $content)
                        <div class="splash-item {{ $index === 0 ? '' : 'hidden' }}" data-index="{{ $index }}">
                            @if($content->material_path)
                                @if($content->isImage())
                                    <img src="{{ $content->url }}" alt="{{ $content->titulo }}" class="w-full h-auto object-cover rounded-t-2xl">
                                @elseif($content->isPdf())
                                    <div class="bg-gray-100 p-6 flex flex-col items-center justify-center rounded-t-2xl">
                                        <i class="fas fa-file-pdf text-red-500 text-6xl mb-4"></i>
                                        <p class="text-lg font-bold text-gray-800 mb-2">{{ $content->titulo }}</p>
                                        <a href="{{ $content->url }}" target="_blank" class="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700 transition">
                                            <i class="fas fa-eye mr-2"></i>Visualizar PDF
                                        </a>
                                    </div>
                                @endif
                            @endif
                            <div class="p-6">
                                <h3 class="text-2xl font-bold text-gray-800 mb-3">{{ $content->titulo }}</h3>
                                @if($content->texto_conteudo)
                                    <p class="text-gray-700 leading-relaxed">{{ $content->texto_conteudo }}</p>
                                @endif
                            </div>
                        </div>
                    @endforeach
                </div>

                @if(session('splash_contents')->count() > 1)
                    <div class="absolute bottom-4 left-0 right-0 flex justify-center gap-2 p-2">
                        @foreach(session('splash_contents') as $index => $content)
                            <button class="splash-dot w-3 h-3 rounded-full bg-gray-300 {{ $index === 0 ? 'bg-blue-600' : '' }}"
                                    onclick="showSplashItem({{ $index }})"></button>
                        @endforeach
                    </div>
                @endif

                <div class="p-4 border-t border-gray-200 flex justify-end">
                    <button onclick="nextSplashItem()" class="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition">
                        <span id="splash-next-btn-text">Próximo</span> <i class="fas fa-arrow-right ml-2"></i>
                    </button>
                </div>
            </div>
        </div>

        <script>
            let currentSplashIndex = 0;
            const splashItems = document.querySelectorAll('.splash-item');
            const splashDots = document.querySelectorAll('.splash-dot');
            const splashNextBtnText = document.getElementById('splash-next-btn-text');
            const totalSplashItems = splashItems.length;

            function showSplashManagerModal() {
                document.getElementById('splash-manager-modal').classList.remove('hidden');
                document.getElementById('splash-manager-modal').classList.add('flex');
            }

            function closeSplashManagerModal() {
                document.getElementById('splash-manager-modal').classList.add('hidden');
                document.getElementById('splash-manager-modal').classList.remove('flex');
            }

            function showSplashItem(index) {
                splashItems.forEach((item, i) => {
                    item.classList.toggle('hidden', i !== index);
                });
                splashDots.forEach((dot, i) => {
                    dot.classList.toggle('bg-blue-600', i === index);
                    dot.classList.toggle('bg-gray-300', i !== index);
                });
                currentSplashIndex = index;
                if (currentSplashIndex === totalSplashItems - 1) {
                    splashNextBtnText.textContent = 'Entendi';
                } else {
                    splashNextBtnText.textContent = 'Próximo';
                }
            }

            function nextSplashItem() {
                if (currentSplashIndex < totalSplashItems - 1) {
                    showSplashItem(currentSplashIndex + 1);
                } else {
                    closeSplashManagerModal();
                }
            }

            document.addEventListener('DOMContentLoaded', () => {
                if (totalSplashItems > 0) {
                    showSplashManagerModal();
                    showSplashItem(0); // Garante que o primeiro item é exibido
                }
            });
        </script>
    @endif

        <div class="max-w-7xl mx-auto px-4 text-center">
            <p>&copy; 2026 64 Bits Soluções. Todos os direitos reservados.</p>
        </div>
    </footer>

    <script>
        (function(){
            const navToggle = document.getElementById('nav-toggle');
            const mobileMenu = document.getElementById('mobile-menu');
            const userDesktopToggle = document.getElementById('user-desktop-toggle');
            const userDesktopMenu = document.getElementById('user-desktop-menu');
            const adminDesktopToggle = document.getElementById('admin-desktop-toggle');
            const adminDesktopMenu = document.getElementById('admin-desktop-menu');

            if(navToggle && mobileMenu){
                navToggle.addEventListener('click', function(){
                    mobileMenu.classList.toggle('hidden');
                });
            }

            if(adminDesktopToggle && adminDesktopMenu){
                adminDesktopToggle.addEventListener('click', function(e){
                    e.stopPropagation();
                    if(userDesktopMenu) userDesktopMenu.classList.add('hidden');
                    adminDesktopMenu.classList.toggle('hidden');
                });
            }

            if(userDesktopToggle && userDesktopMenu){
                userDesktopToggle.addEventListener('click', function(e){
                    e.stopPropagation();
                    if(adminDesktopMenu) adminDesktopMenu.classList.add('hidden');
                    userDesktopMenu.classList.toggle('hidden');
                });
            }

            // close when clicking outside
            document.addEventListener('click', function(){
                if(adminDesktopMenu && !adminDesktopMenu.classList.contains('hidden')){
                    adminDesktopMenu.classList.add('hidden');
                }
                if(userDesktopMenu && !userDesktopMenu.classList.contains('hidden')){
                    userDesktopMenu.classList.add('hidden');
                }
            });
        })();
        // Transform tables inside .table-responsive into card lists on small screens
        (function(){
            const BREAKPOINT = 640;
            function transformTables(){
                document.querySelectorAll('.table-responsive, .overflow-x-auto').forEach(function(container){
                    if (container.classList.contains('no-transform')) return;
                    const table = container.querySelector('table');
                    if(!table) return;
                    // ensure we only process once per container
                    if(container.querySelector('.table-card-list')) return;

                    const thead = table.querySelector('thead');
                    const headers = [];
                    if(thead){
                        thead.querySelectorAll('th').forEach(h => headers.push(h.textContent.trim()));
                    }

                    const list = document.createElement('div');
                    list.className = 'table-card-list';

                    const tbody = table.querySelector('tbody');
                    if(!tbody) return;
                    tbody.querySelectorAll('tr').forEach(function(row){
                        const card = document.createElement('div');
                        card.className = 'table-card';
                        const cells = row.querySelectorAll('td');
                        cells.forEach(function(cell, idx){
                            const rowDiv = document.createElement('div');
                            rowDiv.className = 'table-card-row';
                            const label = document.createElement('div');
                            label.className = 'table-card-label';
                            label.textContent = headers[idx] || '';
                            const value = document.createElement('div');
                            value.className = 'table-card-value';
                            value.innerHTML = cell.innerHTML;
                            rowDiv.appendChild(label);
                            rowDiv.appendChild(value);
                            card.appendChild(rowDiv);
                        });
                        list.appendChild(card);
                    });

                    container.appendChild(list);
                });
            }

            function onResize(){
                if(window.innerWidth <= BREAKPOINT){
                    transformTables();
                }
            }

            window.addEventListener('resize', onResize);
            document.addEventListener('DOMContentLoaded', onResize);
            // also run immediately in case DOM already loaded
            setTimeout(onResize, 50);
        })();
    </script>
    @yield('extra_js')
</body>
</html>
