services:
  app-dss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:9000
    volumes:
      - app_database:/var/www/app/database
      - app_storage:/var/www/app/storage
      - ./public/images:/var/www/app/public/images

volumes:
  app_database:
  app_storage: